version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  frontend:
    build:
      context: ./frontend-app/frontendchatapp
      dockerfile: Dockerfile
    ports:
      - 4200:80